### ISSUE TITLE
When the card is in sidebar, the full screen feature should appear on the entire screen.

### ISSUE THREAD

**Issue by kaipingyang** [rstudio/bslib#1078] opened 2024-06-17 09:15 UTC
Hi teams, I have a suggestion as follows:
When the card is in a sidebar, the full screen feature should be displayed on the entire screen instead of full screen in the sidebar.

The test code is as follows:
```r
library(shiny)
library(bslib)
library(ggplot2)

ui <- page_sidebar(
  title = "Example dashboard",
  sidebar = sidebar(
    varSelectInput("var", "Select variable", mtcars),
    card(
      full_screen = TRUE,
      card_header("table"),
      dataTableOutput("table")
    )
  ),
  card(
    full_screen = TRUE,
    card_header("My plot"),
    plotOutput("p")
  )

)

server <- function(input, output) {
  output$table <- renderDataTable({
    mtcars
  })
  output$p <- renderPlot({
    ggplot(mtcars) + geom_histogram(aes(!!input$var))
  })
}

shinyApp(ui, server)
```

We can see that when we click the full screen button when the card is in the sidebar, the card just goes full screen in the sidebar, which is not what we expected.
![image](https://github.com/rstudio/bslib/assets/55199277/1c0c7bb7-a03f-4153-81fc-63933ff7a406)

In the main panel, the full screen feature of the card is the desired effect.
![image](https://github.com/rstudio/bslib/assets/55199277/852ed974-1fac-484b-b97b-2d2eeb8ff8ef)

```[tasklist]
### Tasks
```

**Comment by gadenbuie** [comment] 2024-07-11 18:42
Duplicate of #1008. Thanks for reporting and providing an additional reprex!

**Closed by gadenbuie** 2024-07-11 18:42 UTC
