### ISSUE TITLE
thematic fails to adequatly style plot with session$setCurrentTheme

### ISSUE THREAD

**Issue by DivadNojnarg** [rstudio/bslib#151] opened 2020-11-04 16:05 UTC
![Screen Recording 2020-11-04 at 16 48 46](https://user-images.githubusercontent.com/18291543/98133819-585c5e00-1ebe-11eb-8906-95da122c7386.gif)

`thematic_shiny` does not work as expected in the following code, the rendering is out of phase.

I am working with : thematic_0.1.0.9000    shiny_1.5.0.9004      bootstraplib_0.2.1.9000

```r
library(bootstraplib)
library(shiny)
library(thematic)
default <- bs_theme()

neon_theme <- bs_theme(
  bg = "#000000", 
  fg = "#FFFFFF", 
  primary = "#9600FF", 
  secondary = "#1900A0",
  success = "#38FF12",
  info = "#00F5FB",
  warning = "#FFF100",
  danger = "#FF00E3",
  base_font = "Marker Felt",
  heading_font = "Marker Felt",
  code_font = "Chalkduster"
)

thematic_shiny()
ui <- fluidPage(
  theme = default, 
  div(
    class = "custom-control custom-switch", 
    tags$input(
      id = "custom_mode", type = "checkbox", class = "custom-control-input",
      onclick = HTML("Shiny.setInputValue('dark_mode', document.getElementById('custom_mode').value);")
    ),
    tags$label(
      "Custom mode?", `for` = "custom_mode", class = "custom-control-label"
    )
  ),
  sliderInput("obs", "Number of observations:",
    min = 0, max = 1000, value = 500
  ),
  plotOutput("distPlot")
)
server <- function(input, output, session) {
  observeEvent(input$custom_mode, {
    session$setCurrentTheme(
      if (isTRUE(input$custom_mode)) neon_theme else default
    )
  })
  
  output$distPlot <- renderPlot({
    hist(rnorm(input$obs))
  })
}
shinyApp(ui, server)
```

**Comment by cpsievert** [comment] 2020-11-04 16:16
Thanks for noticing! This is duplicate of https://github.com/rstudio/shiny/issues/3119, so when that is closed/fixed, that should resolve this issue.

Also, as a heads-up, we're about to rename the package to bslib https://github.com/rstudio/bootstraplib/pull/150

**Closed** 2020-11-06 00:03 UTC
